# Generated by Django 2.0.5 on 2018-06-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='logo',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
